# Generated by Django 4.2.5 on 2023-09-30 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_rename_customer_booking_customer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travellist',
            name='point',
        ),
        migrations.AddField(
            model_name='customuser',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travellist',
            name='homestay_img',
            field=models.FileField(blank=True, null=True, upload_to='assets/homestay_img'),
        ),
        migrations.AddField(
            model_name='travellist',
            name='pano_img',
            field=models.FileField(blank=True, null=True, upload_to='assets/pano'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(default=0)),
                ('travel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.travellist')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
