# Generated by Django 4.2.5 on 2023-10-01 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_remove_travellist_point_customuser_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travellist',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
